# Generated by Django 6.0 on 2026-04-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], db_index=True, max_length=10)),
                ('motivo', models.TextField()),
                ('regla_disparada', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('revisada', models.BooleanField(default=False)),
                ('resolucion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESCARTADA', 'Descartada'), ('CONFIRMADA', 'Confirmada')], default='PENDIENTE', max_length=15)),
            ],
        ),
    ]
