# Generated by Django 6.0 on 2026-04-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antifraud', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertafraude',
            name='cuenta_afectada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.cuenta'),
        ),
        migrations.AddField(
            model_name='alertafraude',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.transaccion'),
        ),
    ]
