# Generated by Django 6.0 on 2026-04-21 22:39

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(db_index=True, default=core.models.generate_account_number, max_length=20, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('CAJA_AHORRO', 'Caja de Ahorro'), ('CUENTA_CORRIENTE', 'Cuenta Corriente')], default='CAJA_AHORRO', max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('limite_transferencia_diaria', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('SOSPECHOSA', 'Sospechosa')], db_index=True, default='PENDIENTE', max_length=15)),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro')], max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('cuenta_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_destino', to='core.cuenta')),
                ('cuenta_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_origen', to='core.cuenta')),
            ],
            options={
                'indexes': [models.Index(fields=['cuenta_origen', 'fecha'], name='core_transa_cuenta__04f542_idx')],
            },
        ),
    ]
