# Generated by Django 6.0 on 2026-04-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FCI', 'Fondo Común de Inversión'), ('PLAZO_FIJO', 'Plazo Fijo')], default='FCI', max_length=20)),
                ('monto_invertido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rendimiento_diario_estimado', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('fecha_inversion', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='core.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.cuenta')),
            ],
        ),
    ]
